PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(1,'Akomodasi Perkantoran');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(2,'Akomodasi Perhotelan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(3,'Akuntansi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(4,'Akomodasi dan Keuangan Lembaga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(5,'Analisa Kesehatan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(6,'Animasi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(7,'Bisnis Daring dan Pemasaran');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(8,'Broadcasting');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(9,'Desain Grafis');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(10,'Desain Interior dan Landscapping');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(11,'Desain Komunikasi Visual');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(12,'Desain Pemodelan dan Informasi Bangungan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(13,'Desain Web');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(14,'Farmasi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(15,'Fotografi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(16,'Jasa Butik');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(17,'Keperawatan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(18,'Kimia Industri');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(19,'Konstruksi Gedung , Sanitasi dan Perawatan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(20,'Kria Kayu');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(21,'Kria Kulit');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(22,'Multimedia');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(23,'Neutika Kapal Niaga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(24,'Otomatisasi dan Tata Kelola Perkantoran');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(25,'Pemasaran');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(26,'Pengawasan Mutu Pangan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(27,'Perawatan Kesehatan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(28,'Perbankan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(29,'Perdagangan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(30,'Rekayasa Perangkat Lunak / Software Programming');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(31,'Sistem Informatika, Jaringan dan Aplikasi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(32,'Tata Boga Restoran');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(33,'Tata Boga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(34,'Tata Busana');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(35,'Tata Kecantikan Kulit');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(36,'Tata Kecantikan Rambut');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(37,'Tata Laksana Kapal Niaga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(38,'Teknik Audio Video / Elektronika');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(39,'Teknik dan Bisnis Sepeda Motor');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(40,'Teknik dan Manajemen Perawatan Otomotif');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(41,'Teknik Elektronika Daya dan Komunikasi');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(42,'Teknik Elektronika Industri');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(43,'Teknik Fabrikasi Logam dan Manufakturing');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(44,'Teknik Gambar Bangunan dan Konstruksi Batu Beton');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(45,'Teknik Gambar Bangunan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(46,'Teknik Instalasi Pemesinan Kapal');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(47,'Teknik Instalasi Tenaga Listrik');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(48,'Teknik Kendaraan Ringan Otomotif');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(49,'Teknik Komputer dan Jaringan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(50,'Teknik Konstruksi Batu Beton');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(51,'Teknik Konstruksi dan Properti');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(52,'Teknik Konstruksi Kapal Baja');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(53,'Teknik Mesin Kapal Niaga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(54,'Teknik Otomasi Industri');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(55,'Teknik Otomotif');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(56,'Teknik Pemesinan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(57,'Teknik Pendingin dan Tata Udara');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(58,'Teknik Pengelasan');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(59,'Teknik Produksi dan Penyiaran Radio dan Pertevilisian');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(60,'Teknik Sepeda Motor');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(61,'Teknik Tenaga Listrik');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(62,'Teknika Kapal Niaga');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(63,'Usaha Jasa Pariwisata');
INSERT INTO jurusan(ID_JURUSAN, NAMA_JURUSAN) VALUES(64,'Videografi');

COMMIT;
